{"label": "test_search_in_python_org", "file": "/Users/sidnarang/Desktop/JWC_SN/jenkins/2016-09-13_15-53-03.540476/classes/test_SeleniumDemo.py", "full_name": "test_SeleniumDemo.PythonOrgSearch.test_search_in_python_org", "status": "BROKEN", "description": null, "start_time": 1473807184.056449, "duration": 30.238728046417236, "error_msg": "WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/rz/llsy0wqx4zn6qw066kpv7l8r0000gn/T/tmpF2e7Q4 If you specified a log_file in the FirefoxBinary constructor, check it for details.", "error_trace": "Traceback (most recent call last):\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 322, in run\n    self.setUp()\n  File \"/Users/sidnarang/Desktop/JWC_SN/jenkins/2016-09-13_15-53-03.540476/classes/test_SeleniumDemo.py\", line 9, in setUp\n    self.driver = webdriver.Firefox()\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py\", line 80, in __init__\n    self.binary, timeout)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py\", line 52, in __init__\n    self.binary.launch_browser(self.profile, timeout=timeout)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 68, in launch_browser\n    self._wait_until_connectable(timeout=timeout)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 108, in _wait_until_connectable\n    % (self.profile.path))\nWebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/rz/llsy0wqx4zn6qw066kpv7l8r0000gn/T/tmpF2e7Q4 If you specified a log_file in the FirefoxBinary constructor, check it for details."}
{"label": "test_search_in_python_org", "file": "/Users/sidnarang/Desktop/JWC_SN/jenkins/2016-09-13_15-53-03.540476/classes/test_SeleniumDemo.py", "full_name": "test_SeleniumDemo.PythonOrgSearch.test_search_in_python_org", "status": "BROKEN", "description": null, "start_time": 1473807214.29977, "duration": 30.168011903762817, "error_msg": "WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/rz/llsy0wqx4zn6qw066kpv7l8r0000gn/T/tmpOQK_Qp If you specified a log_file in the FirefoxBinary constructor, check it for details.", "error_trace": "Traceback (most recent call last):\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 322, in run\n    self.setUp()\n  File \"/Users/sidnarang/Desktop/JWC_SN/jenkins/2016-09-13_15-53-03.540476/classes/test_SeleniumDemo.py\", line 9, in setUp\n    self.driver = webdriver.Firefox()\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py\", line 80, in __init__\n    self.binary, timeout)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py\", line 52, in __init__\n    self.binary.launch_browser(self.profile, timeout=timeout)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 68, in launch_browser\n    self._wait_until_connectable(timeout=timeout)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 108, in _wait_until_connectable\n    % (self.profile.path))\nWebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/rz/llsy0wqx4zn6qw066kpv7l8r0000gn/T/tmpOQK_Qp If you specified a log_file in the FirefoxBinary constructor, check it for details."}
{"label": "test_search_in_python_org", "file": "/Users/sidnarang/Desktop/JWC_SN/jenkins/2016-09-13_15-53-03.540476/classes/test_SeleniumDemo.py", "full_name": "test_SeleniumDemo.PythonOrgSearch.test_search_in_python_org", "status": "BROKEN", "description": null, "start_time": 1473807244.473495, "duration": 4.0617640018463135, "error_msg": "WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.", "error_trace": "Traceback (most recent call last):\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py\", line 322, in run\n    self.setUp()\n  File \"/Users/sidnarang/Desktop/JWC_SN/jenkins/2016-09-13_15-53-03.540476/classes/test_SeleniumDemo.py\", line 9, in setUp\n    self.driver = webdriver.Firefox()\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py\", line 80, in __init__\n    self.binary, timeout)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py\", line 52, in __init__\n    self.binary.launch_browser(self.profile, timeout=timeout)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 68, in launch_browser\n    self._wait_until_connectable(timeout=timeout)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 99, in _wait_until_connectable\n    \"The browser appears to have exited \"\nWebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details."}
